"""Add category column to events table

Revision ID: fc6ca9121bed
Revises: ed1b7c9e38b8
Create Date: 2025-02-01 20:20:22.748095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6ca9121bed'
down_revision = 'ed1b7c9e38b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
